apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - deployment-bff.yaml
  - network-policy.yaml
  - network-policy-bff.yaml
  - service-account.yaml
  - service.yaml
  - service-bff.yaml
images:
  - name: legacy-maliev-intranet-compatibility
    newName: REGION-docker.pkg.dev/PROJECT/legacy/legacy-maliev-intranet-compatibility
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
  - name: legacy-maliev-intranet-bff
    newName: REGION-docker.pkg.dev/PROJECT/legacy/legacy-maliev-intranet-bff
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
