apiVersion: v1
kind: Service
metadata:
  name: legacy-maliev-intranet-bff
  namespace: maliev-legacy
spec:
  selector:
    app.kubernetes.io/name: legacy-maliev-intranet-bff
  ports:
    - name: http
      port: 80
      targetPort: http
